### ISSUE TITLE
Can't find where to add rego

### ISSUE THREAD

**Issue by weaverbel** [resbaz/resbaz2017#27]
Hi @DamienIrving I can't see the spot where I should link our rego form which is ready to go.
I'll see what others have done.

**Comment by weaverbel** [comment]
Figured it out

**Comment by DamienIrving** [comment]
Ah, yes, there isn't a place in the header of the `brisbane.html` (or `template.html`) to put the link for registration. That's because last time some people got fancy and made click buttons for their page (i.e. we didn't really settle on a standard). This is the section of `brisbane.html` that you'll need to edit directly:

```
<!-- Registration -->
<section id="registerSection">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1>Come along</h1>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <p>Coming soon.</p>
            </div>
        </div>
    </div>
</section>
```

**Comment by DamienIrving** [comment]
If you want to be fancy I suggest browsing https://feb2016.resbaz.com/ and then copying the relevant html from https://github.com/resbaz/resbaz-2016-02-01/tree/gh-pages/_posts

**Comment by weaverbel** [comment]
Beat you to it by a minute ;-) 

I'm going to add a bit more info but am treading carefully I promise @DamienIrving
