### ISSUE TITLE
Sydney ResBaz site

### ISSUE THREAD

**Issue by weaverbel** [resbaz/resbaz2017#31]
Can a Sydney page please be created with @ccronje at the manager of it?

**Comment by DamienIrving** [comment]
Sure. No problem. 

@ccronje - Do you want to have a go at creating a Sydney page following the instructions in the [README](https://github.com/resbaz/resbaz2017/blob/gh-pages/README.md)? You can use this issue thread to post any questions you have during the process :smile:

**Comment by ccronje** [comment]
Thanks @DamienIrving - can you please give @KT-Boundary (Kayla) and @jmem727 (Jen) access? They've kindly agreed to take on this role of managing the Sydney site. The three of us were on the ResBaz community call yesterday :-)

**Comment by KT-Boundary** [comment]
Thanks for adding us @DamienIrving 
Would it be best for us to create a branch for sydney while we get everything set up, or do you have a different preferred workflow?

**Comment by DamienIrving** [comment]
@KT-Boundary For your initial commit (i.e. to create the Sydney page following the instructions in the README) I'd suggest forking the repository and then submitting a pull request when you're ready. (You can probably just work on the main gh-pages branch in your fork rather than creating a new branch.) I can then review that initial pull request before merging it.

Your page doesn't have to be complete before you submit the PR - you can leave some placeholders for things like the names of sponsors. As long as the major information is there like the date and location of the event.

Normally I don't give people write access to the repository - like you and @jmem727 have got - until after they've done their initial pull request. This workflow will then be consistent with what the other sites have done. (i.e. once people have successfully submitted a pull request to get their page setup I give them write access so they can make minor changes to the page directly without having to have someone review every little change)

Does that make sense?

**Comment by KT-Boundary** [comment]
@DamienIrving I think that makes sense to me! I'm definitely more comfortable working in a fork until I've got my feet. I'll have a go and let you know if anything doesn't make sense.
