### ISSUE TITLE
Brisbane page is broken

### ISSUE THREAD

**Issue by weaverbel** [resbaz/resbaz2017#64]
Help. I added links today and now the site is kaput - looks horrible. I CANNOT see what is wrong and am really starting to HATE THIS TEMPLATE. It is SO FLAKY.
Can anyone see what is wrong? 

PLEASE?????? Thanks,

**Comment by DamienIrving** [comment]
Was it working at this commit two days ago? (i.e. I'm trying to determine whether links are allowed in session titles at all)
https://github.com/resbaz/resbaz2017/commit/a01799ea52ce0b1ca7d88ee8f19dad7d0107ea0b

**Comment by weaverbel** [comment]
Yes

**Comment by weaverbel** [comment]
I am happy to remove the links if need be. The page was fine until I edited it today.
Sorry Damien!

**Comment by weaverbel** [comment]
It appears to be working now but the schedule looks awful with that pre-ResBaz 6 Feb workshop taking up what should be our first day's slot.

**Comment by DamienIrving** [comment]
It's not your fault. The template is terrible.

The problem is the loop at line 168. It loops over all the sessions defined at the top of brisbane.html, but those sessions (as you know) are super temperamental and don't like things like colons (and now it seems they don't like links that much either). A way around it (if you can be bothered) is to remove that loop at line 168 and just write all the session information in manually. You'll see I've done that for some sections of hobart.html (like the sponsors section). I just deleted the template loop and wrote in the html directly.

**Comment by weaverbel** [comment]
Thanks Damien
I took out 6 Feb (with great trepidation) but the page is still OK. I am not game to monkey with the template and next year someone else can wrangle it. Thanks so much for helping - such a hassle !!!!!! I might try template wrangling when back at work but I am still on holiday so no chance ;-)

**Comment by weaverbel** [comment]
Closing now we are live again
