### ISSUE TITLE
ResBaz 2018 site?

### ISSUE THREAD

**Issue by philippbayer** [resbaz/resbaz2017#94]
Last year at WA's ResBaz we unfortunately managed to finalise the program pretty late so that many supervisors were hesitant to give their students 3 days off ('why would I send my people if I cannot see what they're learning?'). I'd like to get the 2018 WA program up and running asap (we already got a few confirmed sessions and a tentative room booking), but there's no new ResBaz site yet - could we clone this repo into 'resbaz2018' and just start to hack away?

**Comment by DamienIrving** [comment]
Hey, @philippbayer. Great to hear you're starting to get organised already!

We are in talks with Mozilla Science Lab about them possibly taking over the global coordination of ResBaz and we've also been thinking about upgrading the website template, so it probably isn't a good idea to clone this repo to create a resbaz2018 just yet.

A number of ResBaz 2017 sites (e.g. Vancouver) created their own website (rather than use the template) and we just linked to that off the main page, so perhaps that would be a way forward for WA?

**Comment by philippbayer** [comment]
I see! That's an interesting development, didn't know that, but should help tremendously! will this have any impact on the local resbazs?

Seeing that lots is still out to decide I'm closing this issue, for now :)
